### ISSUE TITLE
How to make preview loading time faster?

### ISSUE THREAD

**Issue by DesignerMike93** [lonekorean/mini-preview#5]
I am using this solution for my client. There is a page where I implemented this for loading of 50+ previews, but it really drags down the loading time of the landing page. Currently this minipreview is the best solution and I keep using it in spite of loading times because my client has insisted on it, but I was wondering if there are ways to make previews load faster?

Something like making iframe load only portion of the website for preview? Lowering the quality of the displayed preview? Perhaps even loading a single div from the page from which preview is generated from? I would modify it by myself to test it, but I don't know how to code this.

Could you please help me further with this or suggest a piece of code I could add to achieve this? Thanks in advance.

**Comment by lonekorean** [comment]
Hello! Sounds like all the mini-previews on your page are set to load upon `pageload`. You can change/delay when they load. Two examples:

```js
$('a').miniPreview({ prefetch: 'parenthover' });
$('a').miniPreview({ prefetch: 'none' });
```

`parenthover` will start loading mini-previews when a parent element is hovered (for example, moving the mouse over a paragraph containing the link).

`none` does no preloading. So there will be no upfront slowdown, but mini-previews won't start loading until the link is hovered.

**Comment by DesignerMike93** [comment]
Thank you for the response. I have tested other prefetches and even with individual lazy loading, the previews load too slowly. I know that one aspect of the problem is that the landing pages on my client's site have some content that takes time to render, but what I am wondering is that maybe there is a way, any way possible, to make the loading faster?

[Here is a preview video I made to show you the loading with prefetch: 'parenthover' to illustrate the problem.](https://watch.screencastify.com/v/qTD5a4cIbg5uerBmDkWX)

**Comment by lonekorean** [comment]
Hm, one other thought, if you're not already, can you delay when you make the `$('a').miniPreview()` call(s)? So something like:

```js
window.addEventListener('DOMContentLoaded', () => {
  $('a').miniPreview();
});
```

That should wait until the landing page has loaded before trying to load your other 50 iframed pages. It might still compete for bandwidth with images on your landing page, so you could also try `'load'` instead of `'DOMContentLoaded'`.

**Comment by DesignerMike93** [comment]
Sorry for late reply. Just implemented it now and it's a rather good compromise, made the page itself to load faster. Thanks for assisting me.
